import {
  Injectable,
  Logger,
  NotFoundException,
  BadRequestException,
  ServiceUnavailableException,
  OnModuleInit,
} from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import axios from 'axios';
import type { Response } from 'express';
import { PrismaService, Prisma } from '../prisma/prisma.service';
import { AiService } from '../ai/ai.service';
import { FacebookGraphService, type FbConversation, type FbMessage } from './facebook-graph.service';
import { CskhInboxService } from './cskh-inbox.service';
import {
  buildFacebookOAuthUrl,
  getFacebookAppId,
  getFacebookAppSecret,
  getFacebookOAuthRedirectUri,
  verifyOAuthState,
  GRAPH_BASE,
} from './facebook-oauth.util';
import { isAllowedFacebookMediaUrl } from './facebook-message.util';
import { detectAdFromFbMessages } from './facebook-referral.util';
import { trimTranscriptForAi, type TranscriptLine } from './audit-analytics.util';
import { toUserFacingError } from '../common/user-facing-error.util';

/** Page CSKH đang bật — trường dùng trong monitor/audit (tránh phụ thuộc export Prisma model). */
type EnabledFacebookPage = {
  pageId: string;
  pageName: string | null;
  pageAccessToken: string;
};

@Injectable()
export class CskhService implements OnModuleInit {
  private readonly logger = new Logger(CskhService.name);
  private readonly delayBetweenMs = Number(process.env.CSKH_DELAY_BETWEEN_MS || 800);
  /** Monitor: số hội thoại gần nhất cần quét / Page. */
  private readonly monitorMax = Number(process.env.CSKH_MONITOR_MAX_CONVERSATIONS || 10);
  private readonly auditMax = Number(process.env.CSKH_AUDIT_MAX_CONVERSATIONS || 0);
  /** Cron ban đêm: số cuộc hội thoại gần nhất / kênh. */
  private readonly auditCronMax = Number(process.env.CSKH_AUDIT_CRON_MAX || 30);
  /** Số ngày lùi khi quét (manual + cron) — lấy hội thoại mới nhất trong khoảng này. */
  private readonly auditDefaultLookbackDays = Number(
    process.env.CSKH_AUDIT_LOOKBACK_DAYS || 30,
  );
  /** Số hội thoại chấm AI song song (tăng = nhanh hơn, cẩn thận rate limit AI/Meta). */
  private readonly auditConcurrency = Number(process.env.CSKH_AUDIT_CONCURRENCY || 4);
  /** Số hội thoại fetch tin FB song song / batch. */
  private readonly auditFetchConcurrency = Number(process.env.CSKH_AUDIT_FETCH_CONCURRENCY || 6);
  /** Số Page quét FB song song (khi bật nhiều page). */
  private readonly auditPageConcurrency = Number(process.env.CSKH_AUDIT_PAGE_CONCURRENCY || 2);
  private readonly auditMsgLimit = Number(process.env.CSKH_AUDIT_MSG_LIMIT || 100);
  private readonly auditSource = process.env.CSKH_AUDIT_SOURCE || 'facebook';
  /** Tối đa dòng transcript gửi AI (DB vẫn lưu đủ). */
  private readonly auditAiTranscriptMax = Number(process.env.CSKH_AUDIT_AI_TRANSCRIPT_MAX || 100);
  private readonly auditProgressEvery = Math.max(
    1,
    Number(process.env.CSKH_AUDIT_PROGRESS_EVERY || 40),
  );
  private readonly monitorMaxPages = Number(process.env.CSKH_MONITOR_MAX_PAGES || 10);
  private readonly monitorPageConcurrency = Number(process.env.CSKH_MONITOR_PAGE_CONCURRENCY || 3);
  /** Số hội thoại fetch messages song song / Page (tăng tốc monitor). */
  private readonly monitorMsgConcurrency = Number(process.env.CSKH_MONITOR_MSG_CONCURRENCY || 8);

  private readonly activeJobs = new Map<string, { pauseRequested: boolean }>();

  constructor(
    private readonly prisma: PrismaService,
    private readonly aiService: AiService,
    private readonly graph: FacebookGraphService,
    private readonly config: ConfigService,
    private readonly inboxService: CskhInboxService,
  ) {}

  /** BE restart → job cũ không còn worker, đánh dấu failed để UI không treo. */
  async onModuleInit() {
    const n = await this.prisma.cskhJobRun.updateMany({
      where: { status: 'running' },
      data: {
        status: 'failed',
        error: 'Server khởi động lại — vui lòng chạy job mới',
        finishedAt: new Date(),
      },
    });
    if (n.count > 0) {
      this.logger.warn(`Đã hủy ${n.count} CSKH job kẹt do server restart`);
    }
  }

  async cancelRunningJobs(type: 'monitor' | 'audit', reason = 'Đã hủy bởi người dùng', tenantId?: string) {
    const where: any = { type, status: 'running' };
    if (tenantId) where.tenantId = tenantId;
    const running = await this.prisma.cskhJobRun.findMany({
      where,
      select: { id: true },
    });
    for (const j of running) {
      this.activeJobs.delete(j.id);
      if (type === 'audit') {
        // Delete all chat audits generated by this cancelled job run to keep DB clean
        try {
          await this.prisma.$executeRaw`
            DELETE FROM chat_audits
            WHERE metadata->>'jobRunId' = ${j.id}
          `;
          this.logger.log(`Deleted partial chat audits for cancelled job ${j.id}`);
        } catch (err) {
          this.logger.error(`Failed to delete partial audits for job ${j.id}: ${(err as Error).message}`);
        }
      }
    }
    const result = await this.prisma.cskhJobRun.updateMany({
      where,
      data: { status: 'failed', error: reason, finishedAt: new Date() },
    });
    return result.count;
  }

  /** Tạm dừng audit — chấm xong phần đã quét, lần sau audit cùng ngày sẽ tiếp tục. */
  async requestAuditPause(tenantId?: string) {
    const job = await this.findRunningJob('audit', tenantId);
    if (!job) {
      return { paused: false, message: 'Không có job audit đang chạy' };
    }
    const active = this.activeJobs.get(job.id);
    if (active) {
      active.pauseRequested = true;
    } else {
      this.activeJobs.set(job.id, { pauseRequested: true });
    }
    await this.updateJobProgress(job.id, { pauseRequested: true });
    this.logger.log(`Audit pause requested job=${job.id.slice(0, 8)}`);
    return { paused: true, jobId: job.id };
  }

  /** Job đã bị hủy (status không còn running). */
  private async isAuditJobCancelled(jobId: string): Promise<boolean> {
    if (!this.activeJobs.has(jobId)) {
      const job = await this.prisma.cskhJobRun.findUnique({
        where: { id: jobId },
        select: { status: true },
      });
      return !job || job.status !== 'running';
    }
    return false;
  }

  /** Dừng quét / chấm: tạm dừng hoặc hủy (job không còn running). */
  private async shouldStopAuditJob(jobId: string): Promise<boolean> {
    const mem = this.activeJobs.get(jobId);
    if (mem && mem.pauseRequested) {
      return true;
    }
    const job = await this.prisma.cskhJobRun.findUnique({
      where: { id: jobId },
      select: { status: true, summary: true },
    });
    if (!job || job.status !== 'running') {
      if (mem) this.activeJobs.delete(jobId);
      return true;
    }
    const summary = job.summary as Record<string, unknown> | null;
    const pauseRequested = Boolean(summary?.pauseRequested);
    if (pauseRequested) {
      if (mem) mem.pauseRequested = true;
      return true;
    }
    return false;
  }

  private async loadAuditedConversationKeys(
    auditDateFrom: string,
    auditDateTo: string,
    pageIds: string[],
  ): Promise<Set<string>> {
    if (!pageIds.length) return new Set();

    type Row = {
      conversationId: string | null;
      pageId: string | null;
      participantPsid: string | null;
    };

    const rows = await this.prisma.$queryRaw<Row[]>`
      SELECT
        metadata->>'conversationId' AS "conversationId",
        metadata->>'pageId' AS "pageId",
        metadata->>'participantPsid' AS "participantPsid"
      FROM chat_audits
      WHERE metadata->>'pageId' = ANY(${pageIds}::text[])
        AND (
          (
            metadata->>'auditDateFrom' = ${auditDateFrom}
            AND metadata->>'auditDateTo' = ${auditDateTo}
          )
          OR (
            ${auditDateFrom} = ${auditDateTo}
            AND metadata->>'auditDate' = ${auditDateFrom}
            AND COALESCE(metadata->>'auditDateFrom', '') = ''
          )
        )
    `;

    const keys = new Set<string>();
    for (const row of rows) {
      const pageId = row.pageId?.trim();
      if (!pageId) continue;
      const convId = row.conversationId?.trim();
      const psid = row.participantPsid?.trim();
      if (convId) keys.add(`${pageId}:conv:${convId}`);
      if (psid) keys.add(`${pageId}:psid:${psid}`);
    }
    return keys;
  }

  private isConversationAlreadyAudited(
    keys: Set<string>,
    pageId: string,
    conv: FbConversation,
  ): boolean {
    if (keys.has(`${pageId}:conv:${conv.id}`)) return true;
    const psid = this.graph.resolveParticipantPsid(conv.participants, pageId);
    return Boolean(psid && keys.has(`${pageId}:psid:${psid}`));
  }

  /** Một query / danh sách page — tránh N lần findUnique khi chấm hàng nghìn hội thoại. */
  private async loadInboxAdMaps(pageIds: string[]) {
    type InboxAdRow = {
      fromAd: boolean;
      adId: string | null;
      adTitle: string | null;
      referralSource: string | null;
    };
    const byPage = new Map<string, Map<string, InboxAdRow>>();
    if (!pageIds.length) return byPage;

    const rows = await this.prisma.cskhInboxConversation.findMany({
      where: { pageId: { in: pageIds } },
      select: {
        pageId: true,
        participantPsid: true,
        fromAd: true,
        adId: true,
        adTitle: true,
        referralSource: true,
      },
    });
    for (const row of rows) {
      const psid = row.participantPsid?.trim();
      if (!psid) continue;
      let map = byPage.get(row.pageId);
      if (!map) {
        map = new Map();
        byPage.set(row.pageId, map);
      }
      map.set(psid, {
        fromAd: row.fromAd,
        adId: row.adId,
        adTitle: row.adTitle,
        referralSource: row.referralSource,
      });
    }
    return byPage;
  }

  /** Job running nhưng không có tiến trình → coi là treo. */
  private async failGhostJobIfNeeded(
    job: { id: string; status: string; startedAt: Date; summary: unknown },
    auditCount: number,
  ) {
    if (job.status !== 'running') return false;
    const ageMs = Date.now() - job.startedAt.getTime();
    const summary = (job.summary as Record<string, unknown> | null) ?? {};
    const phase = String(summary.phase ?? '');
    const total = Number(summary.total ?? 0);
    const processed = Number(summary.processed ?? 0);
    const fetched = Number(summary.fetched ?? 0);

    // Job audit đang gọi AI — không hủy sớm (AI ~5–8s/conv, DB lưu chậm hơn poll UI).
    if (phase === 'audit' && total > 0) {
      if (ageMs > 60 * 60_000 && processed === 0 && auditCount === 0) {
        await this.prisma.cskhJobRun.update({
          where: { id: job.id },
          data: {
            status: 'failed',
            error: 'Job quá hạn — AI không phản hồi',
            finishedAt: new Date(),
          },
        });
        this.logger.warn(`Hủy audit job ${job.id.slice(0, 8)} — AI timeout (${Math.round(ageMs / 1000)}s)`);
        return true;
      }
      return false;
    }

    if (ageMs < 120_000) return false;

    const noProgress = auditCount === 0 && fetched === 0 && processed === 0;
    if (!noProgress) return false;

    await this.prisma.cskhJobRun.update({
      where: { id: job.id },
      data: {
        status: 'failed',
        error: 'Job treo — không có tiến trình (thử Chạy lại)',
        finishedAt: new Date(),
      },
    });
    this.logger.warn(`Hủy ghost job ${job.id.slice(0, 8)} (phase=${phase}, age ${Math.round(ageMs / 1000)}s)`);
    return true;
  }

  private frontendUrl(): string {
    return this.config.get<string>('FRONTEND_URL', 'http://localhost:5173').replace(/\/$/, '');
  }

  defaultOAuthReturnUrl(): string {
    return `${this.frontendUrl()}/settings?tab=channel`;
  }

  getOAuthStartUrl(returnUrl?: string, tenantId?: string) {
    if (!getFacebookAppId() || !getFacebookAppSecret()) {
      throw new ServiceUnavailableException(
        'Chưa cấu hình FB_APP_ID và FB_APP_SECRET trên BE',
      );
    }
    return buildFacebookOAuthUrl(returnUrl?.trim() || this.defaultOAuthReturnUrl(), tenantId);
  }

  async listPages(tenantId?: string, options?: { month?: string }) {
    type PageListRow = {
      pageId: string;
      pageName: string | null;
      enabled: boolean;
      updatedAt: Date;
      metadata: Prisma.JsonValue | null;
    };
    const pageListSelect = {
      pageId: true,
      pageName: true,
      enabled: true,
      updatedAt: true,
      metadata: true,
    } as const;

    const month = options?.month?.trim();
    const inboundMonth = month && /^\d{4}-\d{2}$/.test(month) ? month : undefined;

    const rows = await this.prisma.facebookCskhConfig.findMany({
      where: tenantId ? { tenantId } : undefined,
      orderBy: [{ enabled: 'desc' }, { pageName: 'asc' }],
      select: pageListSelect,
    });
    const pageIds = rows.map((r) => r.pageId);

    type ConvGroupRow = { pageId: string; _count: { id: number } };
    const emptyConvGroups: ConvGroupRow[] = [];

    const [convCounts, unreadCounts, inboundStatsMap] = await Promise.all([
      pageIds.length
        ? this.prisma.cskhInboxConversation.groupBy({
            by: ['pageId'],
            where: { pageId: { in: pageIds } },
            _count: { id: true },
          })
        : Promise.resolve(emptyConvGroups),
      pageIds.length
        ? this.prisma.cskhInboxConversation.groupBy({
            by: ['pageId'],
            where: { pageId: { in: pageIds }, unreadCount: { gt: 0 } },
            _count: { id: true },
          })
        : Promise.resolve(emptyConvGroups),
      inboundMonth && pageIds.length
        ? this.loadPageInboundMessageStats(inboundMonth, pageIds)
        : Promise.resolve(new Map<string, number>()),
    ]);

    const convCountMap = new Map(convCounts.map((c) => [c.pageId, c._count.id]));
    const unreadCountMap = new Map(unreadCounts.map((c) => [c.pageId, c._count.id]));

    const missingPictureIds = rows
      .filter((r) => !this.pagePictureUrl(r.metadata))
      .map((r) => r.pageId);
    if (missingPictureIds.length) {
      void this.enrichPagePictures(missingPictureIds).catch((e) =>
        this.logger.warn(`enrichPagePictures: ${(e as Error).message}`),
      );
    }

    const oauth = await this.prisma.facebookOAuthSession.findFirst({
      where: tenantId ? { tenantId } : undefined,
      orderBy: { updatedAt: 'desc' },
      select: { fbUserId: true, fbUserName: true, tokenExpiresAt: true, updatedAt: true },
    });

    return {
      pages: rows.map((row) => ({
        pageId: row.pageId,
        pageName: row.pageName,
        enabled: row.enabled,
        updatedAt: row.updatedAt,
        pagePictureUrl: this.pagePictureUrl(row.metadata),
        conversationCount: convCountMap.get(row.pageId) || 0,
        unreadConversationCount: unreadCountMap.get(row.pageId) || 0,
        inboundMessageCount: inboundMonth ? inboundStatsMap.get(row.pageId) || 0 : undefined,
      })),
      inboundMonth: inboundMonth
        ? {
            month: inboundMonth,
            totalInbound: Array.from(inboundStatsMap.values()).reduce((sum, n) => sum + n, 0),
          }
        : undefined,
      statsMeta: inboundMonth
        ? { inboundMonthStats: true as const, requestedMonth: inboundMonth, buildTag: 'inbound-month-v1' }
        : undefined,
      oauthConnected: Boolean(oauth),
      oauthUser: oauth?.fbUserName || oauth?.fbUserId || null,
      oauthUpdatedAt: oauth?.updatedAt || null,
      oauthExpiresAt: oauth?.tokenExpiresAt || null,
    };
  }

  /** Số tin nhắn khách gửi đến (inbound) theo page trong tháng lịch VN (UTC+7). */
  private async loadPageInboundMessageStats(month: string, pageIds: string[]) {
    if (!pageIds.length) return new Map<string, number>();
    const { from, to } = this.monthRangeDays(month);
    const { start, end } = this.graph.vietnamDateRange(from, to);
    type StatRow = { pageId: string; inboundCount: number };
    const rows = await this.prisma.$queryRaw<StatRow[]>`
      SELECT
        c.page_id AS "pageId",
        COUNT(*)::int AS "inboundCount"
      FROM cskh_inbox_messages m
      INNER JOIN cskh_inbox_conversations c ON c.id = m.conversation_id
      WHERE c.page_id IN (${Prisma.join(pageIds)})
        AND (
          m.direction = 'inbound'
          OR m.sender_type = 'customer'
        )
        AND m.sent_at >= ${start}
        AND m.sent_at <= ${end}
      GROUP BY c.page_id
    `;
    return new Map(rows.map((r) => [r.pageId, r.inboundCount]));
  }

  private monthRangeDays(month: string): { from: string; to: string } {
    const [yearStr, monthStr] = month.split('-');
    const year = Number(yearStr);
    const monthNum = Number(monthStr);
    if (
      !Number.isFinite(year) ||
      !Number.isFinite(monthNum) ||
      monthNum < 1 ||
      monthNum > 12
    ) {
      throw new BadRequestException('Tháng không hợp lệ (YYYY-MM)');
    }
    const lastDay = new Date(year, monthNum, 0).getDate();
    return {
      from: `${month}-01`,
      to: `${month}-${String(lastDay).padStart(2, '0')}`,
    };
  }

  private pagePictureUrl(metadata: unknown): string | null {
    if (!metadata || typeof metadata !== 'object') return null;
    const url = (metadata as { pictureUrl?: string }).pictureUrl;
    return typeof url === 'string' && url.startsWith('http') ? url : null;
  }

  private async enrichPagePictures(pageIds: string[]) {
    if (!pageIds.length) return;
    type PagePictureRow = {
      pageId: string;
      pageAccessToken: string;
      metadata: Prisma.JsonValue | null;
    };

    const batchSize = 12;
    for (let i = 0; i < pageIds.length; i += batchSize) {
      const chunk = pageIds.slice(i, i + batchSize);
      const configs: PagePictureRow[] = await this.prisma.facebookCskhConfig.findMany({
        where: { pageId: { in: chunk } },
        select: { pageId: true, pageAccessToken: true, metadata: true },
      });
      await Promise.all(
        configs.map(async (cfg) => {
          const url = await this.graph.getPagePictureUrl(cfg.pageId, cfg.pageAccessToken);
          if (!url) return;
          const prev = (cfg.metadata as Record<string, unknown>) || {};
          await this.prisma.facebookCskhConfig.update({
            where: { pageId: cfg.pageId },
            data: {
              metadata: { ...prev, pictureUrl: url } as Prisma.InputJsonValue,
            },
          });
        }),
      );
    }
  }

  async savePageConfig(
    data: {
      pageId: string;
      pageName?: string;
      pageAccessToken: string;
      metadata?: Record<string, unknown>;
    },
    tenantId?: string,
  ) {
    const pageId = data.pageId?.trim();
    const token = data.pageAccessToken?.trim();
    if (!pageId || !/^\d+$/.test(pageId)) {
      throw new BadRequestException('pageId phải là số (Facebook Page ID)');
    }
    if (!token || token.length < 20) {
      throw new BadRequestException('pageAccessToken không hợp lệ');
    }
    const metadataJson =
      data.metadata === undefined ? undefined : (data.metadata as Prisma.InputJsonValue);
    const row = await this.prisma.facebookCskhConfig.upsert({
      where: { pageId },
      create: {
        pageId,
        pageName: data.pageName?.trim() || null,
        pageAccessToken: token,
        enabled: true,
        metadata: metadataJson,
        tenantId,
      },
      update: {
        pageName: data.pageName?.trim() || undefined,
        pageAccessToken: token,
        metadata: metadataJson,
        tenantId,
      },
    });

    // Auto subscribe to webhooks
    await this.subscribePageToWebhook(pageId, token).catch((e) => {
      this.logger.error(`Auto subscribe failed for page ${pageId}: ${e.message}`);
    });

    return {
      pageId: row.pageId,
      pageName: row.pageName,
      enabled: row.enabled,
      updatedAt: row.updatedAt,
    };
  }

  async setPageEnabled(pageId: string, enabled: boolean, tenantId?: string) {
    const where = tenantId ? { pageId, tenantId } : { pageId };
    const result = await this.prisma.facebookCskhConfig.updateMany({
      where,
      data: { enabled },
    });
    if (result.count === 0) {
      throw new NotFoundException('Không tìm thấy page hoặc không có quyền');
    }
    return { pageId, enabled };
  }

  async setPagesEnabledBulk(enabled: boolean, pageIds?: string[], tenantId?: string) {
    const ids = pageIds?.map((id) => id.trim()) || [];
    const where: any = tenantId ? { tenantId } : {};
    if (ids.length) {
      where.pageId = { in: ids };
    }
    const result = await this.prisma.facebookCskhConfig.updateMany({
      where,
      data: { enabled },
    });
    return { updated: result.count, enabled };
  }

  async deletePage(pageId: string, tenantId?: string) {
    const where = tenantId ? { pageId, tenantId } : { pageId };
    const result = await this.prisma.facebookCskhConfig.deleteMany({
      where,
    });
    if (result.count === 0) {
      throw new NotFoundException('Không tìm thấy page hoặc không có quyền');
    }
    return { ok: true, pageId };
  }

  private async exchangeCodeForUserToken(code: string): Promise<string> {
    const redirectUri = getFacebookOAuthRedirectUri();
    const shortRes = await axios.get(`${GRAPH_BASE}/oauth/access_token`, {
      params: {
        client_id: getFacebookAppId(),
        client_secret: getFacebookAppSecret(),
        redirect_uri: redirectUri,
        code,
      },
      timeout: 30000,
    });
    const shortToken = shortRes.data?.access_token as string | undefined;
    if (!shortToken) throw new BadRequestException('Meta không trả access_token');

    const longRes = await axios.get(`${GRAPH_BASE}/oauth/access_token`, {
      params: {
        grant_type: 'fb_exchange_token',
        client_id: getFacebookAppId(),
        client_secret: getFacebookAppSecret(),
        fb_exchange_token: shortToken,
      },
      timeout: 30000,
    });
    const longToken = longRes.data?.access_token as string | undefined;
    if (!longToken) throw new BadRequestException('Không đổi được long-lived token');
    return longToken;
  }

  private async fetchManagedPages(userAccessToken: string) {
    type FbPage = {
      id: string;
      name: string;
      access_token: string;
      tasks?: string[];
      picture?: { data?: { url?: string } };
    };
    type FbAccountsResponse = { data?: FbPage[]; paging?: { next?: string } };

    const pages: FbPage[] = [];
    let nextUrl: string | null = `${GRAPH_BASE}/me/accounts`;
    let useParams = true;
    const params: Record<string, string | number> = {
      fields: 'id,name,access_token,tasks,picture{url}',
      limit: 100,
      access_token: userAccessToken,
    };

    while (nextUrl) {
      const res: { data: FbAccountsResponse } = await axios.get<FbAccountsResponse>(nextUrl, {
        params: useParams ? params : undefined,
        timeout: 60000,
      });
      useParams = false;
      const body: FbAccountsResponse = res.data;
      if (Array.isArray(body.data)) pages.push(...body.data);
      nextUrl = body.paging?.next ?? null;
    }
    return pages;
  }

  private async upsertPagesFromAccounts(
    accounts: Array<{
      id: string;
      name: string;
      access_token: string;
      tasks?: string[];
      picture?: { data?: { url?: string } };
    }>,
    source: 'oauth' | 'refresh',
    tenantId?: string,
  ) {
    const validAccounts = accounts.filter((acc) => acc.id && acc.access_token);
    
    // Process all pages concurrently using Promise.all
    const results = await Promise.all(
      validAccounts.map(async (acc) => {
        try {
          const canMessage = !acc.tasks?.length || acc.tasks.includes('MESSAGING');
          const pictureUrl = acc.picture?.data?.url ?? null;
          const existing = await this.prisma.facebookCskhConfig.findUnique({
            where: { pageId: acc.id },
            select: { metadata: true },
          });
          const prevMeta = (existing?.metadata as Record<string, unknown>) || {};
          const meta = {
            ...prevMeta,
            connectedVia: source,
            tasks: acc.tasks || [],
            ...(pictureUrl ? { pictureUrl } : {}),
            refreshedAt: new Date().toISOString(),
          } as Prisma.InputJsonValue;

          await this.prisma.facebookCskhConfig.upsert({
            where: { pageId: acc.id },
            create: {
              pageId: acc.id,
              pageName: acc.name || null,
              pageAccessToken: acc.access_token,
              enabled: canMessage,
              tenantId,
              metadata: {
                connectedVia: source,
                tasks: acc.tasks || [],
                ...(pictureUrl ? { pictureUrl } : {}),
              } as Prisma.InputJsonValue,
            },
            update: {
              pageName: acc.name || undefined,
              pageAccessToken: acc.access_token,
              enabled: canMessage,
              tenantId,
              metadata: meta,
            },
          });

          // Auto subscribe to webhooks
          await this.subscribePageToWebhook(acc.id, acc.access_token).catch((e) => {
            this.logger.error(`Auto subscribe failed for page ${acc.id} via OAuth: ${e.message}`);
          });

          return true;
        } catch (e: any) {
          this.logger.error(`Failed to upsert page ${acc.id} via ${source}: ${e.message}`);
          return false;
        }
      }),
    );

    const savedCount = results.filter(Boolean).length;
    return savedCount;
  }

  async handleOAuthCallback(code: string, state: string) {
    const parsed = verifyOAuthState(state);
    if (!parsed) throw new BadRequestException('OAuth state không hợp lệ');

    const tenantId = parsed.tenantId;
    const userAccessToken = await this.exchangeCodeForUserToken(code);
    const meRes = await axios.get(`${GRAPH_BASE}/me`, {
      params: { fields: 'id,name', access_token: userAccessToken },
      timeout: 30000,
    });
    const fbUserId = String(meRes.data?.id || '');
    const fbUserName = (meRes.data?.name as string | undefined) || null;
    if (!fbUserId) throw new BadRequestException('Không lấy được Facebook user id');

    const accounts = await this.fetchManagedPages(userAccessToken);
    if (!accounts.length) {
      throw new BadRequestException(
        'Tài khoản Facebook không có Page nào — cần quyền quản trị Page trong Business Manager',
      );
    }

    await this.prisma.facebookOAuthSession.upsert({
      where: { fbUserId },
      create: {
        fbUserId,
        fbUserName,
        userAccessToken,
        tenantId,
        metadata: { pageCount: accounts.length } as Prisma.InputJsonValue,
      },
      update: {
        fbUserName,
        userAccessToken,
        tenantId,
        metadata: {
          pageCount: accounts.length,
          reconnectedAt: new Date().toISOString(),
        } as Prisma.InputJsonValue,
      },
    });

    const saved = await this.upsertPagesFromAccounts(accounts, 'oauth', tenantId);
    this.logger.log(`Facebook OAuth: ${saved} pages for user ${fbUserName || fbUserId}`);

    return {
      returnUrl: parsed.returnUrl || this.defaultOAuthReturnUrl(),
      pageCount: saved,
      fbUserName,
    };
  }

  async refreshPagesFromOAuth(tenantId?: string) {
    const session = await this.prisma.facebookOAuthSession.findFirst({
      where: tenantId ? { tenantId } : undefined,
      orderBy: { updatedAt: 'desc' },
    });
    if (!session) {
      throw new NotFoundException('Chưa kết nối OAuth — bấm "Kết nối Facebook" trước');
    }
    const accounts = await this.fetchManagedPages(session.userAccessToken);
    const saved = await this.upsertPagesFromAccounts(accounts, 'refresh', session.tenantId || tenantId);
    return { pageCount: saved, oauthUser: session.fbUserName || session.fbUserId };
  }

  private async enabledPages(tenantId?: string): Promise<EnabledFacebookPage[]> {
    return this.prisma.facebookCskhConfig.findMany({
      where: { enabled: true, tenantId: tenantId || undefined },
      orderBy: { pageName: 'asc' },
      select: { pageId: true, pageName: true, pageAccessToken: true },
    });
  }

  /** Mọi Page đã kết nối — dùng khi chấm điểm (chọn kênh trên FE). */
  private async allPages(tenantId?: string): Promise<EnabledFacebookPage[]> {
    return this.prisma.facebookCskhConfig.findMany({
      where: tenantId ? { tenantId } : undefined,
      orderBy: { pageName: 'asc' },
      select: { pageId: true, pageName: true, pageAccessToken: true },
    });
  }

  /** Khoảng ngày quét audit — mặc định N ngày gần nhất (VN). */
  buildAuditDateRange(lookbackDays = this.auditDefaultLookbackDays): {
    auditDateFrom: string;
    auditDateTo: string;
  } {
    const days = Math.max(1, Math.floor(lookbackDays));
    const today = new Date();
    const from = new Date(today.getTime() - days * 24 * 60 * 60 * 1000);
    return {
      auditDateFrom: from.toISOString().split('T')[0],
      auditDateTo: today.toISOString().split('T')[0],
    };
  }

  /** Mọi kênh đã kết nối — dùng cho cron ban đêm. */
  async listConnectedPages(tenantId?: string) {
    return this.prisma.facebookCskhConfig.findMany({
      where: tenantId ? { tenantId } : undefined,
      orderBy: { pageName: 'asc' },
      select: {
        pageId: true,
        pageName: true,
        pageAccessToken: true,
        tenantId: true,
        enabled: true,
      },
    });
  }

  getAuditCronDefaults() {
    return {
      maxConversations: this.auditCronMax,
      lookbackDays: this.auditDefaultLookbackDays,
    };
  }

  async createJob(type: 'monitor' | 'audit', tenantId?: string) {
    const initialSummary =
      type === 'audit'
        ? ({ phase: 'fetch', fetched: 0, pagesProcessed: 0, pagesTotal: 0 } as Prisma.InputJsonValue)
        : undefined;
    return this.prisma.cskhJobRun.create({
      data: { type, status: 'running', summary: initialSummary, tenantId },
    });
  }

  /** Hủy job kẹt (vd. user tắt AI service giữa chừng). */
  async releaseStaleJobs(type: 'monitor' | 'audit', maxAgeMs = 30 * 60 * 1000, tenantId?: string) {
    const cutoff = new Date(Date.now() - maxAgeMs);
    const where: any = { type, status: 'running', startedAt: { lt: cutoff } };
    if (tenantId) {
      where.tenantId = tenantId;
    }
    const stale = await this.prisma.cskhJobRun.findMany({
      where,
      select: { id: true },
    });
    for (const j of stale) {
      this.activeJobs.delete(j.id);
    }
    await this.prisma.cskhJobRun.updateMany({
      where,
      data: {
        status: 'failed',
        error: 'Job quá hạn — đã hủy tự động (có thể do AI service bị tắt)',
        finishedAt: new Date(),
      },
    });
  }

  async findRunningJob(type: 'monitor' | 'audit', tenantId?: string) {
    const where: any = { type, status: 'running' };
    if (tenantId) {
      where.tenantId = tenantId;
    }
    return this.prisma.cskhJobRun.findFirst({
      where,
      orderBy: { startedAt: 'desc' },
    });
  }

  async getRunningJob(type: 'monitor' | 'audit', tenantId?: string) {
    const running = await this.findRunningJob(type, tenantId);
    if (!running) return null;
    return this.getJob(running.id, tenantId);
  }

  async updateJobProgress(jobId: string, summary: Record<string, unknown>) {
    const jsonSummary = JSON.stringify(summary);
    try {
      await this.prisma.$executeRaw`
        UPDATE cskh_job_runs
        SET summary = COALESCE(summary, '{}'::jsonb) || CAST(${jsonSummary} AS jsonb)
        WHERE id = CAST(${jobId} AS uuid) AND status = 'running'
      `;
    } catch (err) {
      this.logger.error(`Lỗi updateJobProgress job ${jobId}: ${(err as Error).message}`);
    }
  }

  private async runWithConcurrency<T>(
    items: T[],
    concurrency: number,
    fn: (item: T, index: number) => Promise<void>,
  ) {
    await this.runWithConcurrencyStoppable(items, concurrency, fn, async () => false);
  }

  private async runWithConcurrencyStoppable<T>(
    items: T[],
    concurrency: number,
    fn: (item: T, index: number) => Promise<void>,
    shouldStop: () => boolean | Promise<boolean>,
  ): Promise<{ stoppedEarly: boolean }> {
    if (!items.length) return { stoppedEarly: false };

    let stoppedEarly = false;
    let nextIndex = 0;
    const workerCount = Math.min(Math.max(concurrency, 1), items.length);
    const workers = Array.from({ length: workerCount }, async () => {
      while (true) {
        if (await shouldStop()) {
          stoppedEarly = true;
          return;
        }
        if (nextIndex >= items.length) return;
        const index = nextIndex++;
        await fn(items[index], index);
      }
    });
    await Promise.all(workers);
    if (!stoppedEarly && (await shouldStop())) stoppedEarly = true;
    return { stoppedEarly };
  }

  async finishJob(
    jobId: string,
    status: 'done' | 'failed',
    summary?: Record<string, unknown>,
    error?: string,
  ) {
    this.activeJobs.delete(jobId);
    const existing = await this.prisma.cskhJobRun.findUnique({
      where: { id: jobId },
      select: { summary: true },
    });
    const merged = {
      ...((existing?.summary as Record<string, unknown> | null) ?? {}),
      ...(summary ?? {}),
    };
    return this.prisma.cskhJobRun.update({
      where: { id: jobId },
      data: {
        status,
        summary: merged as Prisma.InputJsonValue,
        error: error ? toUserFacingError(error) : null,
        finishedAt: new Date(),
      },
    });
  }

  async getJob(jobId: string, tenantId?: string) {
    const job = await this.prisma.cskhJobRun.findFirst({
      where: tenantId ? { id: jobId, tenantId } : { id: jobId },
      include: {
        monitorItems: {
          where: tenantId ? { needsReply: true, tenantId } : { needsReply: true },
          orderBy: { updatedAt: 'desc' },
        },
      },
    });
    if (!job) throw new NotFoundException('Job không tồn tại hoặc không có quyền');
    return {
      ...job,
      error: job.error ? toUserFacingError(job.error) : null,
    };
  }

  async getLatestMonitor(tenantId?: string) {
    const job = await this.prisma.cskhJobRun.findFirst({
      where: tenantId ? { type: 'monitor', status: 'done', tenantId } : { type: 'monitor', status: 'done' },
      orderBy: { finishedAt: 'desc' },
      include: {
        monitorItems: { 
          where: tenantId ? { needsReply: true, tenantId } : { needsReply: true }, 
          orderBy: { updatedAt: 'desc' } 
        },
      },
    });
    return job;
  }

  private buildMonitorItem(
    config: { pageId: string },
    pageName: string | null,
    conv: FbConversation,
    messages: FbMessage[],
  ) {
    let { customerName } = this.graph.participantInfo(conv.participants, config.pageId);
    if (customerName === 'Khách hàng' && messages.length) {
      const fromCustomer = messages.find((m) => String(m.from?.id) !== String(config.pageId));
      customerName = fromCustomer?.from?.name || customerName;
    }
    const noReply = this.graph.needsReply(messages, config.pageId);
    return {
      pageId: config.pageId,
      pageName,
      conversationId: conv.id,
      customerName,
      lastMessage: messages[0]?.message || null,
      needsReply: noReply,
      updatedAt: conv.updated_time ? new Date(conv.updated_time) : null,
    };
  }

  private async fetchMonitorConversations(
    pageId: string,
    token: string,
    maxCount: number,
  ) {
    try {
      return await this.graph.fetchConversationsForMonitor(pageId, token, maxCount);
    } catch (e) {
      this.logger.warn(
        `Monitor fallback N+1 cho Page ${pageId}: ${(e as Error).message}`,
      );
      const conversations = await this.graph.fetchConversations(pageId, token, maxCount);
      await this.runWithConcurrency<FbConversation>(conversations, this.monitorMsgConcurrency, async (conv) => {
        try {
          const messages = await this.graph.fetchMessages(conv.id, token, 1);
          conv.messages = { data: messages };
        } catch (err) {
          this.logger.warn(`Không đọc messages ${conv.id}: ${(err as Error).message}`);
          conv.messages = { data: [] };
        }
      });
      return conversations;
    }
  }

  async runMonitorJob(jobId: string, maxConversations?: number) {
    const maxFetch = maxConversations ?? this.monitorMax;
    try {
      const job = await this.prisma.cskhJobRun.findUnique({ where: { id: jobId } });
      const pages = await this.enabledPages(job?.tenantId || undefined);
      if (!pages.length) {
        throw new BadRequestException('Chưa có Page nào được bật');
      }
      if (pages.length > this.monitorMaxPages) {
        throw new BadRequestException(
          `Đang bật ${pages.length} Page — tối đa ${this.monitorMaxPages} Page/lần. Vào tab Cấu hình, tắt Page không cần monitor.`,
        );
      }

      type EnabledPage = EnabledFacebookPage;

      let totalConversations = 0;
      let totalNoReply = 0;
      const items: Array<{
        pageId: string;
        pageName: string | null;
        conversationId: string;
        customerName: string | null;
        lastMessage: string | null;
        needsReply: boolean;
        updatedAt: Date | null;
      }> = [];

      let pageErrors = 0;
      let pagesProcessed = 0;

      await this.updateJobProgress(jobId, {
        phase: 'scanning',
        pagesTotal: pages.length,
        pagesProcessed: 0,
        maxConversationsPerPage: maxFetch,
      });

      await this.runWithConcurrency<EnabledPage>(
        pages,
        this.monitorPageConcurrency,
        async (config) => {
          try {
            const pageName = config.pageName;
            const conversations = await this.fetchMonitorConversations(
              config.pageId,
              config.pageAccessToken,
              maxFetch,
            );
            totalConversations += conversations.length;

            const pageItems = conversations.map((conv) => {
              const messages = this.graph.latestMessages(conv);
              const item = this.buildMonitorItem(config, pageName, conv, messages);
              if (item.needsReply) totalNoReply++;
              return item;
            });
            items.push(...pageItems);

            if (pageItems.length) {
              await this.prisma.cskhMonitorItem.createMany({
                data: pageItems.map((item) => ({
                  jobRunId: jobId,
                  pageId: item.pageId,
                  pageName: item.pageName,
                  conversationId: item.conversationId,
                  customerName: item.customerName,
                  lastMessage: item.lastMessage,
                  needsReply: item.needsReply,
                  updatedAt: item.updatedAt,
                })),
              });
            }
          } catch (e) {
            pageErrors++;
            this.logger.warn(
              `Monitor bỏ qua Page ${config.pageName || config.pageId}: ${(e as Error).message}`,
            );
          } finally {
            pagesProcessed++;
            await this.updateJobProgress(jobId, {
              phase: 'scanning',
              pagesTotal: pages.length,
              pagesProcessed,
              currentPage: config.pageName || config.pageId,
              totalConversations,
              totalNoReply,
              pageErrors,
              maxConversationsPerPage: maxFetch,
            });
            this.logger.log(
              `Monitor job ${jobId.slice(0, 8)}: ${pagesProcessed}/${pages.length} Page (${config.pageName || config.pageId})`,
            );
          }
        },
      );

      if (!items.length && pageErrors > 0) {
        throw new BadRequestException(
          `Không đọc được inbox — thiếu quyền pages_read_engagement. Meta App → Permissions → bật quyền, rồi OAuth lại.`,
        );
      }

      await this.finishJob(jobId, 'done', {
        totalConversations,
        totalNoReply,
        pageCount: pages.length,
        pageErrors,
        maxConversationsPerPage: maxFetch,
      });
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      await this.finishJob(jobId, 'failed', undefined, msg);
      this.logger.error(`Monitor job ${jobId} failed: ${msg}`);
    }
  }

  async fetchConversationsForAuditFromDb(
    pageId: string,
    auditDateFrom: string,
    auditDateTo?: string,
    msgLimit = 300,
    onProgress?: (scanned: number, matched: number) => void | Promise<void>,
    convFilter?: (conv: FbConversation) => 'include' | 'exclude' | 'stop',
    maxNewMatches = 0,
    onMatch?: (conv: FbConversation) => void | Promise<void>,
  ): Promise<FbConversation[]> {
    const auditDateToResolved = auditDateTo?.trim() || auditDateFrom;
    const { start, end } = this.graph.vietnamDateRange(auditDateFrom, auditDateToResolved);

    // 1. Fetch conversations for this page from local database
    const dbConversations = await this.prisma.cskhInboxConversation.findMany({
      where: {
        pageId,
        messages: {
          some: {
            sentAt: {
              gte: start,
              lte: end,
            },
          },
        },
      },
      orderBy: [{ lastMessageAt: 'desc' }, { updatedAt: 'desc' }],
      select: {
        id: true,
        fbConversationId: true,
        participantPsid: true,
        customerName: true,
        lastMessageAt: true,
        updatedAt: true,
      },
    });

    const matched: FbConversation[] = [];
    let scanned = 0;

    for (const dbConv of dbConversations) {
      scanned++;

      const participants = {
        data: [
          { id: pageId, name: 'Page' },
          { id: dbConv.participantPsid, name: dbConv.customerName || 'Khách hàng' },
        ],
      };

      const conv: FbConversation = {
        id: dbConv.fbConversationId || dbConv.id,
        updated_time: dbConv.lastMessageAt
          ? dbConv.lastMessageAt.toISOString()
          : dbConv.updatedAt.toISOString(),
        participants,
        messages: { data: [] }, // Load messages just-in-time inside worker to prevent OOM
      };
      (conv as any).dbConversationId = dbConv.id;

      if (convFilter) {
        const decision = convFilter(conv);
        if (decision === 'exclude') continue;
        if (decision === 'stop') break;
      }

      matched.push(conv);
      if (onMatch) {
        await onMatch(conv);
      }

      if (scanned % 10 === 0 && onProgress) {
        await onProgress(scanned, matched.length);
      }

      if (maxNewMatches > 0 && matched.length >= maxNewMatches) {
        break;
      }
    }

    if (onProgress) {
      await onProgress(scanned, matched.length);
    }

    return matched;
  }

  private countAuditedForPage(auditedKeys: Set<string>, pageId: string): number {
    let count = 0;
    const prefix = `${pageId}:`;
    for (const key of auditedKeys) {
      if (key.startsWith(prefix)) count++;
    }
    return count;
  }

  async runAuditJob(
    jobId: string,
    options: {
      auditDate?: string;
      auditDateFrom?: string;
      auditDateTo?: string;
      maxConversations?: number;
      force?: boolean;
      pageId?: string;
    },
  ) {
    this.activeJobs.set(jobId, { pauseRequested: false });
    const auditDateFrom = (options.auditDateFrom || options.auditDate || '').trim();
    const auditDateTo = (options.auditDateTo || options.auditDateFrom || options.auditDate || '')
      .trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(auditDateFrom) || !/^\d{4}-\d{2}-\d{2}$/.test(auditDateTo)) {
      throw new BadRequestException('Ngày bắt đầu / kết thúc không hợp lệ (YYYY-MM-DD)');
    }
    if (auditDateFrom > auditDateTo) {
      throw new BadRequestException('Ngày bắt đầu phải trước hoặc bằng ngày kết thúc');
    }
    const maxConversations = options.maxConversations;
    const force = Boolean(options.force);
    const pageId = options.pageId;
    const cap =
      maxConversations && maxConversations > 0
        ? maxConversations
        : this.auditMax > 0
          ? this.auditMax
          : 0;
    try {
      const job = await this.prisma.cskhJobRun.findUnique({ where: { id: jobId } });
      const pageIdTrimmed = pageId?.trim() || undefined;
      let pages: EnabledFacebookPage[] = [];

      if (pageIdTrimmed) {
        const all = await this.allPages(job?.tenantId || undefined);
        pages = all.filter((p) => p.pageId === pageIdTrimmed);
        if (!pages.length) {
          throw new BadRequestException('Kênh không tồn tại — kết nối lại Facebook ở tab Cài đặt');
        }
      } else {
        pages = await this.allPages(job?.tenantId || undefined);
        if (!pages.length) {
          throw new BadRequestException('Không có kênh nào được kết nối để chấm điểm');
        }
      }

      type AuditTask = {
        config: EnabledFacebookPage;
        conv: FbConversation;
      };

      const pageIds = pages.map((p) => p.pageId);
      const auditedKeys = force
        ? new Set<string>()
        : await this.loadAuditedConversationKeys(auditDateFrom, auditDateTo, pageIds);

      const scanAllPages = !pageIdTrimmed;

      // Một kênh: trừ cuộc đã chấm khỏi cap. Tất cả kênh: cap áp dụng riêng từng page.
      if (!scanAllPages && !force && cap > 0) {
        const alreadyAuditedCount = this.countAuditedForPage(auditedKeys, pageIdTrimmed!);
        const effectiveCap = Math.max(0, cap - alreadyAuditedCount);
        if (effectiveCap === 0) {
          await this.finishJob(jobId, 'done', {
            auditDate: auditDateFrom,
            auditDateFrom,
            auditDateTo,
            pageId: pageIdTrimmed,
            allAlreadyAudited: true,
            skippedAlready: alreadyAuditedCount,
            pageCount: pages.length,
            audited: 0,
            maxConversations: cap,
          });
          this.activeJobs.delete(jobId);
          return;
        }
        this.logger.log(
          `Audit job ${jobId.slice(0, 8)}: tiếp tục ${effectiveCap} cuộc còn lại (${alreadyAuditedCount}/${cap} đã chấm)`,
        );
      }

      const queue: AuditTask[] = [];
      let fetchCompleted = false;

      const getNextTask = async (): Promise<AuditTask | null> => {
        while (queue.length === 0) {
          if (fetchCompleted) return null;
          if (await this.shouldStopAuditJob(jobId)) return null;
          await new Promise((resolve) => setTimeout(resolve, 100));
        }
        return queue.shift() || null;
      };

      let skippedAlready = 0;
      let pausedDuringFetch = false;
      const rangeLabel =
        auditDateFrom === auditDateTo
          ? auditDateFrom
          : `${auditDateFrom} → ${auditDateTo}`;

      const inMemorySummary: Record<string, any> = {
        phase: 'fetch',
        auditDate: auditDateFrom,
        auditDateFrom,
        auditDateTo,
        pageId: pageIdTrimmed || null,
        scanAllPages,
        maxConversations: cap > 0 ? cap : null,
        remainingCap: cap > 0 ? cap : null,
        alreadyAudited: scanAllPages ? 0 : this.countAuditedForPage(auditedKeys, pageIdTrimmed || ''),
        fetched: 0,
        scanned: 0,
        pagesTotal: pages.length,
        pagesProcessed: 0,
        skippedAlready,
        force,
        processed: 0,
        audited: 0,
        errors: 0,
        avgScore: 0,
      };

      const reportProgressDb = async (patch: Record<string, unknown>) => {
        Object.assign(inMemorySummary, patch);
        const jsonSummary = JSON.stringify(inMemorySummary);
        try {
          await this.prisma.$executeRaw`
            UPDATE cskh_job_runs
            SET summary = COALESCE(summary, '{}'::jsonb) || CAST(${jsonSummary} AS jsonb)
            WHERE id = CAST(${jobId} AS uuid) AND status = 'running'
          `;
        } catch (err) {
          this.logger.error(`Lỗi cập nhật tiến độ job ${jobId}: ${(err as Error).message}`);
        }
      };

      // Initial progress write
      await reportProgressDb({});

      let pagesFetchDone = 0;
      let lastFetchProgressMs = 0;

      const reportFetchProgress = async (
        patch: Record<string, unknown>,
        force = false,
      ) => {
        const now = Date.now();
        if (!force && now - lastFetchProgressMs < 2500) return;
        lastFetchProgressMs = now;
        await reportProgressDb(patch);
      };

      let audited = 0;
      let errors = 0;
      let processed = 0;
      const scores: number[] = [];
      let totalPromptTokens = 0;
      let totalCompletionTokens = 0;
      let totalTokens = 0;
      let tokenModel = 'deepseek-chat';

      const inboxAdMaps = await this.loadInboxAdMaps(pageIds);
      this.aiService.resetAuditBatchCaches();

      const auditOne = async ({ config, conv }: AuditTask) => {
        if (await this.shouldStopAuditJob(jobId)) return;

        const pageName = config.pageName || 'Facebook Page';

        // Load messages just-in-time from local DB if empty (to optimize memory usage)
        if (this.auditSource === 'database' && (!conv.messages?.data || conv.messages.data.length === 0)) {
          const { end } = this.graph.vietnamDateRange(auditDateFrom, auditDateTo);
          const dbMessages = await this.prisma.cskhInboxMessage.findMany({
            where: {
              conversationId: (conv as any).dbConversationId || conv.id,
              sentAt: { lte: end },
            },
            orderBy: { sentAt: 'desc' },
            take: this.auditMsgLimit,
          });

          const participantPsid = this.graph.resolveParticipantPsid(conv.participants, config.pageId) || 'Customer';

          const fbMessages: FbMessage[] = dbMessages.map((dbMsg) => {
            const fromId = dbMsg.direction === 'outbound' ? config.pageId : participantPsid;
            const fromName = dbMsg.direction === 'outbound' ? 'Staff' : 'Customer';
            const attachments = dbMsg.attachmentUrl
              ? {
                  data: [
                    {
                      url: dbMsg.attachmentUrl,
                      type: dbMsg.messageType || 'text',
                    },
                  ],
                }
              : undefined;

            return {
              id: dbMsg.fbMessageId || dbMsg.id,
              message: dbMsg.text,
              created_time: dbMsg.sentAt.toISOString(),
              from: { id: fromId, name: fromName },
              attachments,
            };
          });

          conv.messages = { data: fbMessages };
        }

        const messages = this.graph.latestMessages(conv);
        const rangeMessages = this.graph.filterMessagesByDateRange(
          messages,
          auditDateFrom,
          auditDateTo,
        );
        const dayMessages = rangeMessages;
        const staffAbsent = !this.graph.hasStaffMessage(rangeMessages, config.pageId);
        const needsFollowUp = this.graph.needsFollowUpOnDay(rangeMessages, config.pageId);
        const noReplyForAi = staffAbsent;
        const transcript = this.graph.messagesToTranscript(rangeMessages, config.pageId);
        const customerName = this.graph.resolveCustomerName(
          conv.participants,
          config.pageId,
          messages,
          transcript,
        );
        const agentName = this.graph.resolveAgentName(
          messages,
          config.pageId,
          pageName,
          transcript,
        );
        const participantPsid = this.graph.resolveParticipantPsid(conv.participants, config.pageId);

        const inboxAd = participantPsid
          ? (inboxAdMaps.get(config.pageId)?.get(participantPsid) ?? null)
          : null;
        const graphAd = detectAdFromFbMessages(messages);
        const fromAd = Boolean(inboxAd?.fromAd || graphAd.fromAd);
        const adId = inboxAd?.adId ?? graphAd.adId ?? null;
        const adTitle = inboxAd?.adTitle ?? graphAd.adTitle ?? null;
        const referralSource = inboxAd?.referralSource ?? graphAd.referralSource ?? null;

        const fullTranscript: TranscriptLine[] =
          transcript.length > 0
            ? transcript
            : [{ sender: 'Customer', type: 'text', text: '(Không có tin nhắn)', timestamp: '' }];
        const aiTranscript = trimTranscriptForAi(fullTranscript, this.auditAiTranscriptMax);

        const result = await this.aiService.auditChat({
          transcript: fullTranscript,
          aiTranscript,
          agentName,
          customerName,
          channel: 'Facebook Messenger',
          noReply: noReplyForAi,
          metadata: {
            jobRunId: jobId,
            conversationId: conv.id,
            pageId: config.pageId,
            pageName,
            participantPsid,
            auditDate: auditDateFrom,
            auditDateFrom,
            auditDateTo,
            auditDayMessageCount: dayMessages.length,
            transcriptMessageCount: rangeMessages.length,
            noReply: needsFollowUp || staffAbsent,
            staffAbsent,
            needsFollowUp,
            fromAd,
            adId,
            adTitle,
            referralSource,
          },
        });

        if (result && typeof result === 'object' && 'error' in result && result.error) {
          errors++;
        } else if (result && 'id' in result) {
          audited++;
          scores.push(Number((result as { score?: number }).score) || 0);
          const tu = (result as {
            tokenUsage?: {
              prompt_tokens?: number;
              completion_tokens?: number;
              total_tokens?: number;
              model?: string;
            };
          }).tokenUsage;
          if (tu) {
            totalPromptTokens += Number(tu.prompt_tokens) || 0;
            totalCompletionTokens += Number(tu.completion_tokens) || 0;
            totalTokens += Number(tu.total_tokens) || 0;
            if (tu.model) tokenModel = tu.model;
          }

          // Auto-link/upsert and sync messages to inbox + analyze intent (awaited to ensure
          // customerIntent is persisted in metadata before progress reports the audit row)
          if (participantPsid) {
            const tenantId = job?.tenantId || undefined;
            const latestMsgs = this.graph.latestMessages(conv);
            try {
              await this.inboxService.autoLinkAndSync(
                (result as { id: string }).id,
                conv,
                latestMsgs,
                config.pageId,
                config.pageAccessToken,
                customerName,
                tenantId,
              );
            } catch (err) {
              this.logger.warn(`Auto link and sync inbox conversation failed: ${(err as Error).message}`);
            }
          }
        }

        processed++;
        const tokenUsageSummary = {
          model: tokenModel,
          promptTokens: totalPromptTokens,
          completionTokens: totalCompletionTokens,
          totalTokens,
          perAuditAvg: processed > 0 ? Math.round(totalTokens / processed) : 0,
        };
        await reportProgressDb({
          phase: fetchCompleted ? 'audit' : 'fetch',
          total: fetchCompleted ? inMemorySummary.fetched : undefined,
          processed,
          audited,
          errors,
          avgScore: scores.length
            ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length)
            : 0,
          currentCustomer: customerName,
          tokenUsage: tokenUsageSummary,
        });
      };

      // Start the audit consumer workers in the background
      const workerPromises = Array.from({ length: this.auditConcurrency }, async () => {
        while (true) {
          if (await this.shouldStopAuditJob(jobId)) break;
          const task = await getNextTask();
          if (!task) break;
          await auditOne(task);
        }
      });

      const pageScannedMap = new Map<string, number>();

      try {
        const { stoppedEarly: pausedDuringFetchPages } = await this.runWithConcurrencyStoppable(
          pages.map((config, pageIndex) => ({ config, pageIndex })),
          this.auditPageConcurrency,
          async ({ config, pageIndex }) => {
            const pageName = config.pageName || config.pageId;
            let effectiveCapForPage = cap;
            if (!force && cap > 0) {
              const pageAudited = this.countAuditedForPage(auditedKeys, config.pageId);
              effectiveCapForPage = Math.max(0, cap - pageAudited);
              if (effectiveCapForPage === 0) {
                pagesFetchDone++;
                this.logger.log(
                  `Audit job ${jobId.slice(0, 8)}: Page ${pageName} — đã đủ ${cap} cuộc, bỏ qua`,
                );
                await reportFetchProgress(
                  { pagesProcessed: pagesFetchDone, currentPage: pageName },
                  true,
                );
                return;
              }
            }
            try {
              await reportFetchProgress({
                currentPage: pageName,
              });

              let skippedOnPage = 0;
              let pageMatchedCount = 0;
              let conversations: FbConversation[] = [];
              let usingDb = false;

              const onMatch = async (conv: FbConversation) => {
                pageMatchedCount++;
                queue.push({ config, conv });
                inMemorySummary.fetched = (inMemorySummary.fetched || 0) + 1;
                await reportFetchProgress({
                  fetched: inMemorySummary.fetched,
                });
              };

              if (this.auditSource === 'database') {
                this.logger.log(`[CskhService] Thử nghiệm quét từ database cục bộ cho Page ${pageName}...`);
                conversations = await this.fetchConversationsForAuditFromDb(
                  config.pageId,
                  auditDateFrom,
                  auditDateTo,
                  this.auditMsgLimit,
                  async (scanned, matchedOnPage) => {
                    pageScannedMap.set(config.pageId, scanned);
                    const totalScanned = Array.from(pageScannedMap.values()).reduce((a, b) => a + b, 0);
                    await reportFetchProgress({
                      scanned: totalScanned,
                      currentPage: pageName,
                    });
                  },
                  (conv) => {
                    if (this.isConversationAlreadyAudited(auditedKeys, config.pageId, conv)) {
                      skippedOnPage++;
                      return 'exclude';
                    }
                    return 'include';
                  },
                  effectiveCapForPage > 0 ? effectiveCapForPage : 0,
                  onMatch,
                );
                if (conversations.length > 0) {
                  usingDb = true;
                } else {
                  this.logger.warn(
                    `[CskhService] Không tìm thấy cuộc hội thoại nào trong database cho Page ${pageName} trong khoảng ${rangeLabel}. ` +
                      `Tự động fallback sang quét trực tiếp từ Facebook API...`,
                  );
                }
              }

              if (!usingDb) {
                conversations = await this.graph.fetchConversationsForAuditByDate(
                  config.pageId,
                  config.pageAccessToken,
                  auditDateFrom,
                  auditDateTo,
                  this.auditMsgLimit,
                  async (scanned, matchedOnPage) => {
                    pageScannedMap.set(config.pageId, scanned);
                    const totalScanned = Array.from(pageScannedMap.values()).reduce((a, b) => a + b, 0);
                    await reportFetchProgress({
                      scanned: totalScanned,
                      currentPage: pageName,
                    });
                  },
                  this.auditFetchConcurrency,
                  () => this.shouldStopAuditJob(jobId),
                  (conv) => {
                    if (this.isConversationAlreadyAudited(auditedKeys, config.pageId, conv)) {
                      skippedOnPage++;
                      return 'exclude';
                    }
                    return 'include';
                  },
                  effectiveCapForPage > 0 ? effectiveCapForPage : 0,
                  onMatch,
                );
              }

              pagesFetchDone++;
              skippedAlready += skippedOnPage;

              this.logger.log(
                `Audit job ${jobId.slice(0, 8)}: Page ${pageName} — ${rangeLabel}: chấm ${pageMatchedCount} cuộc mới` +
                  (cap > 0 ? ` (giới hạn ${cap})` : '') +
                  `, bỏ qua ${skippedOnPage} đã chấm`,
              );

              await reportFetchProgress(
                {
                  pagesProcessed: pagesFetchDone,
                  currentPage: pageName,
                  skippedAlready,
                },
                true,
              );
            } catch (err) {
              this.logger.error(`Lỗi khi quét page ${pageName} (${config.pageId}): ${(err as Error).message}`);
              // Vẫn tăng pagesProcessed để thanh tiến độ không bị kẹt
              pagesFetchDone++;
              await reportFetchProgress(
                {
                  pagesProcessed: pagesFetchDone,
                  currentPage: pageName,
                  skippedAlready,
                },
                true,
              );
            }
          },
          () => this.shouldStopAuditJob(jobId),
        );
        pausedDuringFetch = pausedDuringFetchPages;
      } finally {
        fetchCompleted = true;
      }

      // Wait for all workers to finish
      await Promise.all(workerPromises);

      if (await this.isAuditJobCancelled(jobId)) {
        this.logger.log(`Audit job ${jobId.slice(0, 8)}: đã hủy`);
        return;
      }

      // Fetch is done, all workers done. Check if we fetched anything.
      if (!inMemorySummary.fetched) {
        if (skippedAlready > 0) {
          await this.finishJob(jobId, 'done', {
            auditDate: auditDateFrom,
            auditDateFrom,
            auditDateTo,
            skippedAlready,
            allAlreadyAudited: true,
            pageCount: pages.length,
          });
          return;
        }
        if (pausedDuringFetch) {
          await this.finishJob(jobId, 'done', {
            auditDate: auditDateFrom,
            auditDateFrom,
            auditDateTo,
            paused: true,
            partial: true,
            audited: 0,
            skippedAlready,
            pageCount: pages.length,
          });
          return;
        }
        throw new BadRequestException(
          `Không có hội thoại nào trong khoảng ${rangeLabel}`,
        );
      }

      const pausedDuringAudit = processed < inMemorySummary.fetched && (await this.shouldStopAuditJob(jobId));
      const paused = pausedDuringFetch || pausedDuringAudit;
      const avgScore = scores.length
        ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length)
        : 0;

      await this.finishJob(jobId, 'done', {
        audited,
        errors,
        avgScore,
        pageCount: pages.length,
        total: inMemorySummary.fetched,
        processed,
        auditDate: auditDateFrom,
        auditDateFrom,
        auditDateTo,
        skippedAlready,
        paused,
        partial: paused,
        remaining: paused ? Math.max(0, inMemorySummary.fetched - processed) : 0,
        tokenUsage: {
          model: tokenModel,
          promptTokens: totalPromptTokens,
          completionTokens: totalCompletionTokens,
          totalTokens,
          perAuditAvg: processed > 0 ? Math.round(totalTokens / processed) : 0,
        },
      });
    } catch (e) {
      if (await this.isAuditJobCancelled(jobId)) {
        this.logger.log(`Audit job ${jobId.slice(0, 8)}: đã hủy (bỏ qua lỗi hậu kỳ)`);
        return;
      }
      const msg = e instanceof Error ? e.message : String(e);
      await this.finishJob(jobId, 'failed', undefined, msg);
      this.logger.error(`Audit job ${jobId} failed: ${msg}`);
    }
  }

  getDeepSeekBalance() {
    return this.aiService.getDeepSeekBalance();
  }

  /** Token tổng job audit gần nhất (hoặc job đang chạy) — cho stat header FE. */
  async getAuditTokenStats() {
    const running = await this.findRunningJob('audit');
    if (running) {
      const summary = (running.summary as Record<string, unknown> | null) ?? {};
      const tokenUsage = summary.tokenUsage ?? null;
      return {
        source: 'running' as const,
        jobId: running.id,
        finishedAt: running.finishedAt,
        tokenUsage,
      };
    }

    const lastDone = await this.prisma.cskhJobRun.findFirst({
      where: { type: 'audit', status: 'done' },
      orderBy: { finishedAt: 'desc' },
    });
    if (!lastDone) {
      return { source: 'none' as const, jobId: null, finishedAt: null, tokenUsage: null };
    }
    const summary = (lastDone.summary as Record<string, unknown> | null) ?? {};
    return {
      source: 'lastJob' as const,
      jobId: lastDone.id,
      finishedAt: lastDone.finishedAt,
      tokenUsage: summary.tokenUsage ?? null,
    };
  }

  async listAudits(
    params: {
      pageId?: string;
      jobRunId?: string;
      auditDate?: string;
      auditDateFrom?: string;
      auditDateTo?: string;
      limit?: number;
    },
    tenantId?: string,
  ) {
    const limit = Math.min(params.limit ?? 100, 2000);
    if (params.jobRunId) {
      return this.listAuditsByJobRunId(params.jobRunId, limit, tenantId);
    }

    const auditDateFrom = (params.auditDateFrom || params.auditDate || '').trim();
    const auditDateTo = (params.auditDateTo || params.auditDateFrom || params.auditDate || '').trim();
    const pageId = params.pageId?.trim();

    if (auditDateFrom && auditDateTo) {
      type Row = {
        id: string;
        agentName: string | null;
        customerName: string | null;
        channel: string | null;
        score: number;
        feedback: string | null;
        transcript: unknown;
        metadata: unknown;
        createdAt: Date;
      };
      const rows = pageId
        ? await this.prisma.$queryRaw<Row[]>`
            SELECT id, agent_name AS "agentName", customer_name AS "customerName",
              channel, score, feedback, transcript, metadata, created_at AS "createdAt"
            FROM chat_audits
            WHERE metadata->>'pageId' = ${pageId}
              AND (
                (metadata->>'auditDateFrom' = ${auditDateFrom} AND metadata->>'auditDateTo' = ${auditDateTo})
                OR (
                  ${auditDateFrom} = ${auditDateTo}
                  AND metadata->>'auditDate' = ${auditDateFrom}
                  AND COALESCE(metadata->>'auditDateFrom', '') = ''
                )
              )
              AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
            ORDER BY created_at DESC
            LIMIT ${limit}
          `
        : await this.prisma.$queryRaw<Row[]>`
            SELECT id, agent_name AS "agentName", customer_name AS "customerName",
              channel, score, feedback, transcript, metadata, created_at AS "createdAt"
            FROM chat_audits
            WHERE (
                (metadata->>'auditDateFrom' = ${auditDateFrom} AND metadata->>'auditDateTo' = ${auditDateTo})
                OR (
                  ${auditDateFrom} = ${auditDateTo}
                  AND metadata->>'auditDate' = ${auditDateFrom}
                  AND COALESCE(metadata->>'auditDateFrom', '') = ''
                )
              )
              AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
            ORDER BY created_at DESC
            LIMIT ${limit}
          `;
      return this.attachAuditInboxContext(rows);
    }

    const filters = [
      ...(pageId ? [{ metadata: { path: ['pageId'], equals: pageId } }] : []),
      ...(tenantId ? [{ tenantId }] : []),
    ];

    const rows = await this.prisma.chatAudit.findMany({
      where: filters.length ? { AND: filters } : undefined,
      orderBy: { createdAt: 'desc' },
      take: limit,
      select: {
        id: true,
        agentName: true,
        customerName: true,
        channel: true,
        score: true,
        feedback: true,
        transcript: true,
        metadata: true,
        createdAt: true,
      },
    });
    return this.attachAuditInboxContext(rows);
  }

  /** Thống kê nhanh theo khoảng ngày chấm điểm — không tải transcript. */
  async getAuditDayStats(auditDateFrom: string, auditDateTo?: string, pageId?: string, tenantId?: string) {
    const from = auditDateFrom.trim();
    const to = (auditDateTo?.trim() || from).trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(from) || !/^\d{4}-\d{2}-\d{2}$/.test(to)) {
      throw new BadRequestException('Ngày không hợp lệ (YYYY-MM-DD)');
    }
    const pid = pageId?.trim();

    type StatsRow = {
      total: bigint;
      passed: bigint;
      failed: bigint;
      from_ad: bigint;
    };

    const rows = pid
      ? await this.prisma.$queryRaw<StatsRow[]>`
          SELECT
            COUNT(*)::bigint AS total,
            COUNT(*) FILTER (WHERE score >= 70)::bigint AS passed,
            COUNT(*) FILTER (WHERE score < 70)::bigint AS failed,
            COUNT(*) FILTER (WHERE COALESCE(metadata->>'fromAd', 'false') = 'true')::bigint AS from_ad
          FROM chat_audits
          WHERE metadata->>'pageId' = ${pid}
            AND (
              (metadata->>'auditDateFrom' = ${from} AND metadata->>'auditDateTo' = ${to})
              OR (
                ${from} = ${to}
                AND metadata->>'auditDate' = ${from}
                AND COALESCE(metadata->>'auditDateFrom', '') = ''
              )
            )
            AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
        `
      : await this.prisma.$queryRaw<StatsRow[]>`
          SELECT
            COUNT(*)::bigint AS total,
            COUNT(*) FILTER (WHERE score >= 70)::bigint AS passed,
            COUNT(*) FILTER (WHERE score < 70)::bigint AS failed,
            COUNT(*) FILTER (WHERE COALESCE(metadata->>'fromAd', 'false') = 'true')::bigint AS from_ad
          FROM chat_audits
          WHERE (
              (metadata->>'auditDateFrom' = ${from} AND metadata->>'auditDateTo' = ${to})
              OR (
                ${from} = ${to}
                AND metadata->>'auditDate' = ${from}
                AND COALESCE(metadata->>'auditDateFrom', '') = ''
              )
            )
            AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
        `;

    const row = rows[0];
    return {
      auditDate: from,
      auditDateFrom: from,
      auditDateTo: to,
      pageId: pid ?? null,
      total: Number(row?.total ?? 0),
      passed: Number(row?.passed ?? 0),
      failed: Number(row?.failed ?? 0),
      fromAd: Number(row?.from_ad ?? 0),
    };
  }

  /** So sánh điểm NV / team (cùng page) / trung bình ngày — tính từ DB. */
  async getAuditComparisonStats(auditDate: string, auditId: string, tenantId?: string) {
    const day = auditDate.trim();
    if (!/^\d{4}-\d{2}-\d{2}$/.test(day)) {
      throw new BadRequestException('Ngày audit không hợp lệ (YYYY-MM-DD)');
    }

    const audit = await this.prisma.chatAudit.findFirst({
      where: tenantId ? { id: auditId, tenantId } : { id: auditId },
      select: { id: true, score: true, agentName: true, metadata: true },
    });
    if (!audit) throw new NotFoundException('Không tìm thấy audit hoặc không có quyền');

    const meta = (audit.metadata as Record<string, unknown> | null) ?? {};
    const auditDay = String(meta.auditDate ?? '');
    if (auditDay && auditDay !== day) {
      throw new BadRequestException('auditDate không khớp với audit được chọn');
    }

    const pageName = typeof meta.pageName === 'string' ? meta.pageName : null;
    const agentName = audit.agentName?.trim() || null;

    type ScoreRow = { score: number; agent_name: string | null; page_name: string | null };
    const rows = await this.prisma.$queryRaw<ScoreRow[]>`
      SELECT
        score,
        agent_name,
        metadata->>'pageName' AS page_name
      FROM chat_audits
      WHERE metadata->>'auditDate' = ${day}
        AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
    `;

    const scores = rows.map((r) => r.score);
    const overall =
      scores.length > 0 ? Math.round(scores.reduce((a, b) => a + b, 0) / scores.length) : audit.score;

    const staffRows =
      agentName && agentName !== 'Nhân viên'
        ? rows.filter((r) => (r.agent_name ?? '').trim() === agentName)
        : [audit];
    const staff =
      staffRows.length > 0
        ? Math.round(staffRows.reduce((a, r) => a + r.score, 0) / staffRows.length)
        : audit.score;

    const teamRows = pageName
      ? rows.filter((r) => (r.page_name ?? '').trim() === pageName)
      : rows;
    const team =
      teamRows.length > 0
        ? Math.round(teamRows.reduce((a, r) => a + r.score, 0) / teamRows.length)
        : overall;

    return {
      auditDate: day,
      auditId: audit.id,
      staff,
      team,
      overall,
      staffSampleSize: staffRows.length,
      teamSampleSize: teamRows.length,
      daySampleSize: scores.length,
    };
  }

  /** Điểm chất lượng cùng hội thoại qua các ngày audit (nếu được quét nhiều lần). */
  async getAuditScoreHistory(auditId: string, tenantId?: string) {
    const audit = await this.prisma.chatAudit.findFirst({
      where: tenantId ? { id: auditId, tenantId } : { id: auditId },
      select: { id: true, score: true, metadata: true, createdAt: true },
    });
    if (!audit) throw new NotFoundException('Không tìm thấy audit hoặc không có quyền');

    const meta = (audit.metadata as Record<string, unknown> | null) ?? {};
    const pageId = typeof meta.pageId === 'string' ? meta.pageId.trim() : '';
    const conversationId =
      typeof meta.conversationId === 'string' ? meta.conversationId.trim() : '';
    const participantPsid =
      typeof meta.participantPsid === 'string' ? meta.participantPsid.trim() : '';

    type HistoryRow = {
      id: string;
      score: number;
      audit_date: string | null;
      created_at: Date;
    };

    let rows: HistoryRow[] = [];
    if (pageId && (conversationId || participantPsid)) {
      rows = await this.prisma.$queryRaw<HistoryRow[]>`
        SELECT
          id,
          score,
          metadata->>'auditDate' AS audit_date,
          created_at
        FROM chat_audits
        WHERE metadata->>'pageId' = ${pageId}
          AND (
            (${conversationId} <> '' AND metadata->>'conversationId' = ${conversationId})
            OR (${participantPsid} <> '' AND metadata->>'participantPsid' = ${participantPsid})
          )
          AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
        ORDER BY COALESCE(metadata->>'auditDate', '') ASC, created_at ASC
      `;
    }

    if (!rows.length) {
      const day = typeof meta.auditDate === 'string' ? meta.auditDate : '';
      return {
        auditId: audit.id,
        points: [
          {
            auditId: audit.id,
            auditDate: day || audit.createdAt.toISOString().slice(0, 10),
            score: audit.score,
            label: day || 'Hiện tại',
          },
        ],
      };
    }

    const byDay = new Map<string, { auditId: string; auditDate: string; score: number }>();
    for (const row of rows) {
      const auditDate =
        row.audit_date?.trim() || row.created_at.toISOString().slice(0, 10);
      byDay.set(auditDate, {
        auditId: row.id,
        auditDate,
        score: row.score,
      });
    }

    const points = [...byDay.values()].map((p) => ({
      ...p,
      label: p.auditDate,
    }));

    return { auditId: audit.id, points };
  }

  private customerPictureFromMetadata(metadata: unknown): string | null {
    if (!metadata || typeof metadata !== 'object') return null;
    const url = (metadata as { customerPictureUrl?: string }).customerPictureUrl;
    return typeof url === 'string' && url.startsWith('http') ? url : null;
  }

  private auditAdFromMetadata(metadata: unknown): {
    fromAd: boolean;
    adId: string | null;
    adTitle: string | null;
    referralSource: string | null;
  } {
    if (!metadata || typeof metadata !== 'object') {
      return { fromAd: false, adId: null, adTitle: null, referralSource: null };
    }
    const m = metadata as {
      fromAd?: boolean;
      adId?: string | null;
      adTitle?: string | null;
      referralSource?: string | null;
    };
    return {
      fromAd: Boolean(m.fromAd),
      adId: typeof m.adId === 'string' ? m.adId : null,
      adTitle: typeof m.adTitle === 'string' ? m.adTitle : null,
      referralSource: typeof m.referralSource === 'string' ? m.referralSource : null,
    };
  }

  private async attachAuditInboxContext<
    T extends { metadata: unknown; customerName: string | null },
  >(rows: T[]) {
    const needInbox: Array<{ pageId: string; psid: string; index: number }> = [];
    const pictures: Array<string | null> = rows.map((row, index) => {
      const fromMeta = this.customerPictureFromMetadata(row.metadata);
      if (fromMeta) return fromMeta;
      const meta = row.metadata as { pageId?: string; participantPsid?: string } | null;
      if (meta?.pageId && meta?.participantPsid) {
        needInbox.push({ pageId: meta.pageId, psid: meta.participantPsid, index });
      }
      return null;
    });

    const adContext: Array<{
      fromAd: boolean;
      adId: string | null;
      adTitle: string | null;
      referralSource: string | null;
    }> = rows.map((row) => this.auditAdFromMetadata(row.metadata));

    if (needInbox.length) {
      type InboxContextRow = {
        pageId: string;
        participantPsid: string;
        customerPictureUrl: string | null;
        fromAd: boolean;
        adId: string | null;
        adTitle: string | null;
        referralSource: string | null;
      };
      const inboxRows: InboxContextRow[] = await this.prisma.cskhInboxConversation.findMany({
        where: {
          OR: needInbox.map((k) => ({
            pageId: k.pageId,
            participantPsid: k.psid,
          })),
        },
        select: {
          pageId: true,
          participantPsid: true,
          customerPictureUrl: true,
          fromAd: true,
          adId: true,
          adTitle: true,
          referralSource: true,
        },
      });
      const inboxMap = new Map<string, InboxContextRow>(
        inboxRows.map((r) => [`${r.pageId}:${r.participantPsid}`, r]),
      );
      for (const k of needInbox) {
        const inbox = inboxMap.get(`${k.pageId}:${k.psid}`);
        if (!inbox) continue;
        const url = inbox.customerPictureUrl;
        if (typeof url === 'string' && url.startsWith('http')) {
          pictures[k.index] = url;
        }
        if (!adContext[k.index].fromAd && inbox.fromAd) {
          adContext[k.index] = {
            fromAd: true,
            adId: inbox.adId,
            adTitle: inbox.adTitle,
            referralSource: inbox.referralSource,
          };
        }
      }
    }

    return rows.map((row, index) => ({
      ...row,
      customerPictureUrl: pictures[index],
      fromAd: adContext[index].fromAd,
      adId: adContext[index].adId,
      adTitle: adContext[index].adTitle,
      referralSource: adContext[index].referralSource,
    }));
  }

  /** @deprecated alias — dùng attachAuditInboxContext */
  private async attachCustomerPictures<
    T extends { metadata: unknown; customerName: string | null },
  >(rows: T[]) {
    return this.attachAuditInboxContext(rows);
  }

  private async fetchAndCacheCustomerPicture(pageId: string, psid: string): Promise<string | null> {
    const config = await this.prisma.facebookCskhConfig.findUnique({ where: { pageId } });
    if (!config?.pageAccessToken) return null;
    const profile = await this.graph.getMessengerUserProfile(psid, config.pageAccessToken);
    if (!profile.pictureUrl?.startsWith('http')) return null;

    await this.prisma.cskhInboxConversation
      .updateMany({
        where: { pageId, participantPsid: psid },
        data: {
          customerPictureUrl: profile.pictureUrl,
          customerName: profile.name ?? undefined,
        },
      })
      .catch(() => undefined);

    return profile.pictureUrl;
  }

  /** Proxy media Facebook CDN — public (thẻ img/video không gửi JWT). */
  async proxyMediaUrl(rawUrl: string, res: Response) {
    let url = (rawUrl || '').trim();
    if (!url) {
      throw new BadRequestException(
        'Thiếu tham số url — URL phải encode đầy đủ (encodeURIComponent)',
      );
    }
    if (!isAllowedFacebookMediaUrl(url)) {
      throw new BadRequestException('URL media không hợp lệ');
    }
    if (url.startsWith('http://')) {
      url = `https://${url.slice('http://'.length)}`;
    }
    try {
      const upstream = await axios.get(url, {
        responseType: 'stream',
        timeout: 30000,
        maxRedirects: 5,
        headers: {
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
          Referer: 'https://www.facebook.com/',
        },
      });
      res.set('Cache-Control', 'public, max-age=3600');
      res.set('Cross-Origin-Resource-Policy', 'cross-origin');
      const contentType = upstream.headers['content-type'];
      res.set(
        'Content-Type',
        typeof contentType === 'string' ? contentType : 'application/octet-stream',
      );
      upstream.data.pipe(res);
    } catch (e) {
      this.logger.warn(`Failed to proxy media URL: ${(e as Error).message}. Redirecting to original URL.`);
      try {
        if (!res.headersSent) {
          res.redirect(url);
        }
      } catch (redirectErr) {
        this.logger.error(`Failed to redirect: ${(redirectErr as Error).message}`);
        if (!res.headersSent) {
          res.status(404).send('Media not found');
        }
      }
    }
  }

  /** @deprecated Dùng proxyMediaUrl */
  async proxyAvatarUrl(rawUrl: string, res: Response) {
    return this.proxyMediaUrl(rawUrl, res);
  }

  /** Avatar Page — fetch Graph theo pageId rồi stream (public, không JWT). */
  async streamPageAvatar(pageId: string, res: Response) {
    const pid = (pageId || '').trim();
    if (!pid || !/^\d+$/.test(pid)) {
      throw new BadRequestException('pageId không hợp lệ');
    }

    const config = await this.prisma.facebookCskhConfig.findUnique({ where: { pageId: pid } });
    if (!config?.pageAccessToken) {
      throw new NotFoundException('Page chưa liên kết');
    }

    const pictureUrl = await this.graph.getPagePictureUrl(pid, config.pageAccessToken);
    if (!pictureUrl?.startsWith('http')) {
      // Trả về ảnh SVG đại diện mặc định cho Page thay vì báo lỗi 404 để làm sạch log
      const svg = `
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
          <rect width="100" height="100" fill="#EEF2FF"/>
          <rect x="25" y="25" width="50" height="50" rx="10" fill="#6366F1"/>
          <text x="50" y="58" font-family="sans-serif" font-size="24" font-weight="bold" fill="#FFFFFF" text-anchor="middle">P</text>
        </svg>
      `.trim();
      res.type('image/svg+xml');
      return res.send(svg);
    }

    const prev = (config.metadata as Record<string, unknown>) || {};
    await this.prisma.facebookCskhConfig
      .update({
        where: { pageId: pid },
        data: {
          metadata: { ...prev, pictureUrl } as Prisma.InputJsonValue,
        },
      })
      .catch(() => undefined);

    return this.proxyMediaUrl(pictureUrl, res);
  }

  /** Avatar khách — fetch mới từ Graph rồi stream (public, không JWT). */
  async streamCustomerAvatar(pageId: string, psid: string, res: Response) {
    const pid = (pageId || '').trim();
    const uid = (psid || '').trim();
    if (!pid || !uid) throw new BadRequestException('Thiếu pageId hoặc psid');

    const config = await this.prisma.facebookCskhConfig.findUnique({ where: { pageId: pid } });
    if (!config?.pageAccessToken) throw new NotFoundException('Page chưa liên kết');

    let profile: { name: string | null; pictureUrl: string | null };
    try {
      profile = await this.graph.getMessengerUserProfile(uid, config.pageAccessToken);
    } catch {
      profile = { name: null, pictureUrl: null };
    }
    if (!profile.pictureUrl?.startsWith('http')) {
      // Trả về ảnh SVG đại diện mặc định cho Khách hàng để làm sạch log và nâng cao trải nghiệm người dùng
      const svg = `
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" width="100" height="100">
          <rect width="100" height="100" fill="#E2E8F0"/>
          <circle cx="50" cy="35" r="20" fill="#94A3B8"/>
          <path d="M15 85 C15 65, 35 60, 50 60 C65 60, 85 65, 85 85" fill="#94A3B8"/>
        </svg>
      `.trim();
      res.type('image/svg+xml');
      return res.send(svg);
    }

    await this.prisma.cskhInboxConversation
      .updateMany({
        where: { pageId: pid, participantPsid: uid },
        data: {
          customerPictureUrl: profile.pictureUrl,
          customerName: profile.name ?? undefined,
        },
      })
      .catch(() => undefined);

    return this.proxyMediaUrl(profile.pictureUrl, res);
  }

  /** Lấy audit theo jobRunId — dùng raw SQL vì Prisma JSON path filter không ổn định. */
  private async listAuditsByJobRunId(jobRunId: string, limit: number, tenantId?: string) {
    type AuditRow = {
      id: string;
      agentName: string | null;
      customerName: string | null;
      channel: string | null;
      score: number;
      feedback: string | null;
      transcript: unknown;
      metadata: unknown;
      createdAt: Date;
    };
    const rows = await this.prisma.$queryRaw<AuditRow[]>`
      SELECT
        id,
        agent_name AS "agentName",
        customer_name AS "customerName",
        channel,
        score,
        feedback,
        transcript,
        metadata,
        created_at AS "createdAt"
      FROM chat_audits
      WHERE metadata->>'jobRunId' = ${jobRunId}
        AND (${tenantId}::uuid IS NULL OR tenant_id = ${tenantId}::uuid)
      ORDER BY created_at DESC
      LIMIT ${limit}
    `;
    return this.attachCustomerPictures(rows);
  }

  /** Một endpoint gộp: trạng thái job + kết quả audit từ DB (nguồn sự thật cho UI). */
  async getAuditProgress(jobId: string, tenantId?: string, opts?: { includeAudits?: boolean }) {
    const includeAudits = opts?.includeAudits !== false;
    let job = await this.prisma.cskhJobRun.findFirst({
      where: tenantId ? { id: jobId, tenantId } : { id: jobId },
    });
    if (!job) throw new NotFoundException('Job không tồn tại hoặc không có quyền');

    let auditCount = 0;
    let audits: Awaited<ReturnType<typeof this.listAuditsByJobRunId>> = [];
    if (includeAudits) {
      audits = await this.listAuditsByJobRunId(jobId, 500, tenantId);
      auditCount = audits.length;
    } else {
      const countRow = await this.prisma.$queryRaw<{ count: bigint }[]>`
        SELECT COUNT(*)::bigint AS count
        FROM chat_audits
        WHERE metadata->>'jobRunId' = ${jobId}
      `;
      auditCount = Number(countRow[0]?.count ?? 0);
    }

    if (await this.failGhostJobIfNeeded(job, auditCount)) {
      job = await this.prisma.cskhJobRun.findFirst({
        where: tenantId ? { id: jobId, tenantId } : { id: jobId },
      });
      if (!job) throw new NotFoundException('Job không tồn tại hoặc không có quyền');
      if (includeAudits && job.status !== 'running') {
        audits = await this.listAuditsByJobRunId(jobId, 500, tenantId);
        auditCount = audits.length;
      }
    } else if (includeAudits) {
      auditCount = audits.length;
    }

    const summary = (job.summary as Record<string, unknown> | null) ?? {};
    return {
      id: job.id,
      status: job.status,
      error: job.error ? toUserFacingError(job.error) : null,
      startedAt: job.startedAt,
      finishedAt: job.finishedAt,
      summary: {
        ...summary,
        auditCount,
      },
      audits: includeAudits ? audits : [],
    };
  }

  async subscribePageToWebhook(pageId: string, pageAccessToken: string) {
    try {
      const url = `${GRAPH_BASE}/${pageId}/subscribed_apps`;
      const res = await axios.post(
        url,
        null,
        {
          params: {
            subscribed_fields: 'messages,messaging_postbacks,messaging_optins,message_deliveries,message_reads,messaging_referrals',
            access_token: pageAccessToken,
          },
          timeout: 10000,
        }
      );
      this.logger.log(`Subscribed page ${pageId} to webhook successfully: ${JSON.stringify(res.data)}`);
      return res.data;
    } catch (e) {
      const msg = e instanceof Error ? e.message : 'Unknown error';
      this.logger.error(`Failed to subscribe page ${pageId} to webhook: ${msg}`);
      if (axios.isAxiosError(e) && e.response) {
        this.logger.error(`Facebook error response for page ${pageId}: ${JSON.stringify(e.response.data)}`);
      }
      throw e;
    }
  }

  async getDashboardStats(tenantId?: string) {
    const whereTenant = tenantId ? { tenantId } : {};

    const [
      totalPages,
      enabledPages,
      totalAudits,
      avgScoreResult,
      totalConversations,
      totalMessages,
      recentAudits,
      latestJobs,
    ] = await Promise.all([
      this.prisma.facebookCskhConfig.count({ where: whereTenant }),
      this.prisma.facebookCskhConfig.count({ where: { ...whereTenant, enabled: true } }),
      this.prisma.chatAudit.count({ where: whereTenant }),
      this.prisma.chatAudit.aggregate({
        where: whereTenant,
        _avg: { score: true },
      }),
      this.prisma.cskhInboxConversation.count({ where: whereTenant }),
      this.prisma.cskhInboxMessage.count({ where: whereTenant }),
      this.prisma.chatAudit.findMany({
        where: whereTenant,
        orderBy: { createdAt: 'desc' },
        take: 5,
      }),
      this.prisma.cskhJobRun.findMany({
        where: whereTenant,
        orderBy: { startedAt: 'desc' },
        take: 5,
      }),
    ]);

    const avgScore = avgScoreResult._avg.score ? Math.round(avgScoreResult._avg.score) : 0;

    return {
      totalPages,
      enabledPages,
      totalAudits,
      avgScore,
      totalConversations,
      totalMessages,
      recentAudits: recentAudits.map((a) => ({
        id: a.id,
        agentName: a.agentName,
        customerName: a.customerName,
        channel: a.channel,
        score: a.score,
        createdAt: a.createdAt,
      })),
      latestJobs: latestJobs.map((j) => ({
        id: j.id,
        type: j.type,
        status: j.status,
        startedAt: j.startedAt,
        finishedAt: j.finishedAt,
      })),
    };
  }
}
